### PR TITLE
Added additional onError and onComplete parameters to safe Apply and added Typescript definitions

### PR DESCRIPTION
**Pull request by Roaders**
I wanted to run safe apply when errors and onComplete events happened and I want to use with Typescript.

### CODE REVIEW

**Comment by Roaders** [comment]
Thanks for accepting @mattpodwysocki . Any idea when the next version will be released so that I can get this on npm? What is the process for releasing new versions?

**Comment by mattpodwysocki** [comment]
@Roaders will get on it today

**Comment by Roaders** [comment]
great. Thanks

**Comment by Roaders** [comment]
I wasn't sure about including the tsd or typings in there. Not sure if the reference to the angular.d.ts in the rx.angular.d.rs is correct.
Any guidance on this?

**Pull request merged**
